[package]
name = "tdlib-test"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
libloading = "0.7"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
regex = "1.0"
log = "0.4"
env_logger = "0.9"
rusqlite = "0.29.0"
chrono = "0.4"
once_cell = "1.18.0"
dotenv = "0.15"
